# Generated by Django 4.2.6 on 2023-10-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom1', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
                ('symptom2', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25)),
                ('symptom3', models.CharField(choices=[('Graduate', 'Graduated'), ('Not_Graduate', 'Not_Graduate')], max_length=25)),
            ],
        ),
    ]
